name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    secrets: inherit

  deploy:
    name: Deploy
    needs: build
    uses: ./.github/workflows/deploy-train.yaml
    secrets: inherit