name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    with:
      test: true
    secrets: inherit

  release:
    name: Release
    needs: build
    uses: ./.github/workflows/release.yaml
    secrets: inherit