on:
  workflow_call:
    inputs:
      environment:
        type: string

jobs:
  deploy:
    strategy:
      matrix:
        phase: [predeploy, deploy, postdeploy]
      fail-fast: true
      max-parallel: 1
    name: ${{ matrix.phase }} to ${{ inputs.environment }}
    environment: ${{ inputs.environment }}-${{ matrix.phase }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ matrix.phase }}"