on:
  workflow_call:
    inputs:
      environment:
        type: string

jobs:
  predeploy:
    name: "Predeploy"
    runs-on: ubuntu-latest
    steps:
      - run: echo "Predeploy"

  deploy:
    name: "Deploy"
    needs: predeploy
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy"

  postdeploy:
    name: "Postdeploy"
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - run: echo "Postdeploy"