on:
  workflow_call:
    inputs:
      phases:
        type: string
      environment:
        type: string

jobs:
  deploy:
    strategy:
      matrix:
        phase: ${{ fromJson(inputs.phases) }}
      fail-fast: true
      max-parallel: 1
    name: ${{ matrix.phase }} to ${{ inputs.environment }}
    environment: ${{ inputs.environment }}/${{ matrix.phase }}
    concurrency:
      group: ${{ inputs.environment }}
      cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: echo "${{ matrix.phase }} to ${{ inputs.environment }}"