on:
  workflow_call:
    inputs:
      environment:
        type: string

jobs:
  predeploy:
    name: "Predeploy to ${{ inputs.environment }}"
    environment: ${{ inputs.environment }}-pre
    runs-on: ubuntu-latest
    steps:
      - run: echo "Predeploy"

  deploy:
    name: "Deploy to ${{ inputs.environment }}"
    environment: ${{ inputs.environment }}
    needs: predeploy
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy"

  postdeploy:
    name: "Postdeploy to ${{ inputs.environment }}"
    environment: ${{ inputs.environment }}-post
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - run: echo "Postdeploy"