on:
  workflow_call:

jobs:
  dev:
    name: Dev
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: dev
    secrets: inherit

  staging:
    name: Staging
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: dev
    secrets: inherit

  prod:
    needs: staging
    name: Prod
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: dev
    secrets: inherit

#  deploy:
#    strategy:
#      matrix:
#        environment: [dev, staging, prod]
#    name: ${{ matrix.environment }}
#    uses: ./.github/workflows/deploy.yaml
#    with:
#      environment: ${{ matrix.environment }}
#    secrets: inherit